// Code generated by protoc-gen-cache. DO NOT EDIT.
// versions:
// 	protoc-gen-cache test
// 	protoc (unknown)
// source: tenancy.proto
//
// database: tenancy_db
// schema:   tenancy
//
// annotations: entity.v1 test, cache.v1 test
// engine:      protokit test
// runtime:     github.com/the-protobuf-project/runtime-go/cache
//
// cache — https://github.com/the-protobuf-project/cache

package tenancycache

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/the-protobuf-project/cache/examples/generated/gorm/tenancy_db/tenancy"
	"github.com/the-protobuf-project/runtime-go/cache"
)

// This package is the *typed* path onto the cache runtime: one decorator per
// cached resource, implementing the store interface protoc-gen-store generated,
// so a caller narrows to the interface and stops caring which one it holds.
//
// There is a second path, and they are alternatives rather than layers. The
// untyped one is runtime-go/database/cached.Wrap, which decorates a store.Driver
// at the byte level and knows nothing about these types. Stacking both would put
// two caches on one read: the decorator would hit, or miss and call a store whose
// driver caches the same row again under a different key, and an invalidation
// through one would leave the other serving what it just invalidated. Pick one.
//
// # What is not here
//
// Key strings. runtime-go/cache/core/keyspace.go owns key layout entirely. What
// this file generates is the *namespace* the keyspace is built under — the value
// handed to Provider.SetDatabase — and never a key inside it. Two keyspaces that
// have to agree is one keyspace too many.
//
// Singleflight, negative caching, TTL enforcement, stale-while-revalidate and
// index maintenance are all in core, and none of them is reimplemented here.

// Invalidator is the one method an invalidation edge needs.
//
// cache.Aside satisfies it, and so does every decorator in this package, so
// wiring an edge is passing one to the other rather than introducing a type
// whose only purpose is to be passed.
type Invalidator interface {
	Invalidate(ctx context.Context, id string) error
}

// Edge is one declared invalidation relationship: a write to From makes To's
// entries stale.
//
// The set below is data, not machinery. Nothing in this file reads it — each
// edge is also a named field and a straight-line call, so the blast radius of a
// write is visible where the write is. It is emitted because something else will
// want it: a CDC consumer invalidating from the write-ahead log needs to know
// which entries a row change reaches, and should not have to regenerate this
// package to find out.
type Edge struct {
	// From and To are fully-qualified proto message names.
	From, To string

	// Via is the foreign-key column carrying the relationship.
	Via string

	// Reason is why the edge exists, in one line.
	Reason string
}

// InvalidationEdges is every invalidation edge originating in the tenancy
// schema, sorted by (from, to, via).
var InvalidationEdges = []Edge{}

// Option tunes a decorator at construction.
type Option func(*options)

type options struct {
	notFound     func(error) bool
	writeErrors  func(ctx context.Context, resource, op string, err error)
	strictWrites bool
}

// WithNotFound teaches the decorators which store error means "this row does not
// exist", so an absence can be cached.
//
// It has to be supplied because this package cannot ask. Negative caching —
// remembering that something is missing, so a stream of requests for it stops
// reaching the database — engages only when the loader returns an error wrapping
// cache.ErrNotFound, and the generated store returns its driver's error
// unchanged (gorm.ErrRecordNotFound). Translating that here would mean importing
// the driver into generated cache code, which is the coupling this whole
// arrangement exists to avoid.
//
// Without it everything still works: a missing row propagates its error to the
// caller and nothing is cached. What you lose is the protection against a client
// walking ids that do not exist, which is the case negative caching is for.
//
//	store, err := NewCachedAuthorStore(ctx, inner, db,
//	    WithNotFound(func(err error) bool { return errors.Is(err, gorm.ErrRecordNotFound) }))
func WithNotFound(fn func(error) bool) Option {
	return func(o *options) { o.notFound = fn }
}

func newOptions(opts []Option) options {
	var o options
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	return o
}

// asNotFound translates a loader error into one the runtime will cache as an
// absence, leaving every other error alone.
func (o options) asNotFound(err error) error {
	if err == nil || o.notFound == nil || !o.notFound(err) {
		return err
	}
	return fmt.Errorf("%w: %w", cache.ErrNotFound, err)
}

// WithWriteErrors observes cache failures that happen *after* a store write has
// already committed — a refresh, a refile, an edge invalidation.
//
// By default those failures do not reach the caller (see afterWrite), which
// means that without this option they are invisible. That is the trade: the
// alternative default is worse, but silence is not free, and a cache whose
// invalidations have been quietly failing for a week is a cache serving stale
// reads nobody has a signal for. Wire this to a counter or a log line.
//
//	store, err := NewCachedAuthorStore(ctx, inner, db,
//	    WithWriteErrors(func(ctx context.Context, resource, op string, err error) {
//	        slog.ErrorContext(ctx, "cache write-side failure",
//	            "resource", resource, "op", op, "err", err)
//	    }))
func WithWriteErrors(fn func(ctx context.Context, resource, op string, err error)) Option {
	return func(o *options) { o.writeErrors = fn }
}

// WithStrictWrites makes a post-commit cache failure fail the write call.
//
// This is the opposite trade to the default, and it is the right one only when
// serving a stale read is worse than a caller believing a write failed that did
// not. Note what it cannot do: the row is already committed by the time anything
// here runs, so this reports the failure, it does not undo it. A caller that
// retries on the error will write twice.
func WithStrictWrites() Option {
	return func(o *options) { o.strictWrites = true }
}

// afterWrite decides what a committed write does about a cache error that
// followed it.
//
// The default is to report it to the observer, if there is one, and otherwise
// swallow it — and that default is the one deliberate asymmetry in this file, so
// it is worth stating why rather than leaving it to be discovered.
//
// Everything routed through here runs *after* s.inner has already committed the
// row. Returning the error to the caller therefore says "your write failed" about
// a write that succeeded, and the ordinary response to that is a retry — which
// creates a second row, or clobbers a concurrent update, for what was a blip in
// a cache. The failure mode of swallowing is different in kind: an entry stays
// stale until its TTL expires. Bounded, recoverable, and invisible only to
// someone who did not wire WithWriteErrors.
//
// The bound is what makes the trade work, so mind the case that has none: a
// resource with no (cache.v1.cache).ttl keeps entries until something invalidates
// them, and a dropped invalidation there is not stale-for-a-minute but stale
// until the next successful write. Each decorator's doc comment says whether its
// resource has a TTL.
//
// WithStrictWrites restores the other behavior for callers who want it.
func (o options) afterWrite(ctx context.Context, resource, op string, err error) error {
	if err == nil {
		return nil
	}
	if o.writeErrors != nil {
		o.writeErrors(ctx, resource, op, err)
	}
	if o.strictWrites {
		return fmt.Errorf("cache: %s: %s failed after the store write had already committed: %w",
			resource, op, err)
	}
	return nil
}

// assertNamespace is what makes a generated namespace a guarantee rather than a
// suggestion.
//
// A *cache.DB arrives already bound to whatever namespace the caller selected it
// under, and nothing in the type says which. If it is not the one this resource's
// keys were derived for, every read and write in this decorator addresses a
// keyspace the generator never reasoned about — which for a scoped resource means
// the isolation it exists to provide is simply absent. cache.DB.Name is the only
// handle on that, so it is checked here, once, before a decorator exists at all.
func assertNamespace(db *cache.DB, want, resource string) error {
	if db.Name == want {
		return nil
	}
	if db.Name == "" {
		return fmt.Errorf("cache: %s: this cache database was selected by index, not by name, "+
			"so it carries no namespace and the one this decorator's keys are derived for (%q) "+
			"cannot be enforced.\n\nSelect it with Provider.SetDatabase(ctx, %s) instead of "+
			"SelectIndex", resource, want, namespaceFuncName(resource))
	}
	return fmt.Errorf("cache: %s: this cache database is namespaced %q, but this decorator's keys "+
		"are derived under %q.\n\nEvery read and write would address a keyspace other than the one "+
		"generated for this resource. Select the database with Provider.SetDatabase(ctx, %s)",
		resource, db.Name, want, namespaceFuncName(resource))
}

// namespaceFuncName names the generated helper in an error message, so the fix
// is spelled out rather than described.
func namespaceFuncName(resource string) string {
	if i := strings.LastIndex(resource, "."); i >= 0 {
		return resource[i+1:] + "Namespace(...)"
	}
	return "the resource's Namespace function"
}

// assertSets fails construction when the driver behind db has no server-side
// sets.
//
// The strategies that need them do not degrade without them — core refuses, per
// operation, with ErrUnsupported — so a decorator built on a setless backend is
// one whose index accessors all fail at runtime, on a code path a test with a
// real Redis will never reach. Better to refuse at startup, naming the resource
// and the capability, than to hand back something that compiles and cannot work.
//
// It probes rather than asks because there is nothing to ask. core resolves a
// driver's capabilities once, at construction, and keeps them private; *cache.DB
// exposes the four strategies and no report of what is behind them. IDsByIndex on
// an empty value is the cheapest question that has the answer in it: a driver with
// no sets refuses before touching the network, and one with sets answers with an
// empty result.
func assertSets(ctx context.Context, db *cache.DB, resource, strategy, probe string) error {
	if _, err := db.Indexed.IDsByIndex(ctx, probe, ""); errors.Is(err, cache.ErrUnsupported) {
		return fmt.Errorf("cache: %s is configured as %s, which requires core.Sets, and the %s "+
			"backend behind this cache database does not implement it: %w\n\n"+
			"A backend with no server-side sets cannot maintain a secondary index or enumerate "+
			"entries. Either move this resource to STRATEGY_ASIDE or STRATEGY_VOLATILE, or wire "+
			"it to a backend with sets (redis, dragonfly).",
			resource, strategy, db.Backend, err)
	}
	return nil
}

// WARNING: tenancy.v1.Audit: strategy is STRATEGY_INDEXED but no field is marked (cache.v1.cache_index). That is STRATEGY_DOCUMENT with extra bookkeeping — either index a field or change the strategy.

// AuditScope is the parent scope a Audit decorator is bound to.
//
// A decorator is constructed per scope, not per process: the namespace — and so
// every key under it — is parameterized by these values, which is what keeps one
// parent's entries unreachable from another's.
type AuditScope struct {
	// OrgID is the {org} segment of the resource pattern. Every key this decorator reads or writes is namespaced by it, which is what keeps one org's entries unreachable from another's.
	OrgID string
	// Region is the region column, forced into the namespace by (cache.v1.cache_scope).
	Region string
}

// validate rejects a scope that cannot name a keyspace.
//
// An empty value would collapse two parents into one namespace, which is the
// isolation failure this whole mechanism exists to prevent — silently, since the
// resulting name is still a valid name. A ':' would let two differently-spelled
// scopes address the same keys, for the reason core.CheckNamespace gives.
func (s AuditScope) validate() error {
	if s.OrgID == "" {
		return errors.New("cache: tenancy.v1.Audit: scope field OrgID is empty; " +
			"an empty scope value collapses every parent into one namespace, which removes the " +
			"isolation the org segment exists to provide")
	}
	if strings.Contains(s.OrgID, ":") {
		return fmt.Errorf("cache: scope field OrgID = %q contains ':', which the cache "+
			"keyspace uses to join the prefix to the namespace — two scopes spelled differently "+
			"would address the same keys", s.OrgID)
	}
	if s.Region == "" {
		return errors.New("cache: tenancy.v1.Audit: scope field Region is empty; " +
			"an empty scope value collapses every parent into one namespace, which removes the " +
			"isolation the region segment exists to provide")
	}
	if strings.Contains(s.Region, ":") {
		return fmt.Errorf("cache: scope field Region = %q contains ':', which the cache "+
			"keyspace uses to join the prefix to the namespace — two scopes spelled differently "+
			"would address the same keys", s.Region)
	}
	return nil
}

// AuditNamespace returns the namespace Audit's keyspace is built under.
//
// This is the value to pass to Provider.SetDatabase. It is the whole of what this
// generator emits about key layout: core owns everything below it.
func AuditNamespace(scope AuditScope) string {
	return strings.Join([]string{
		"audit",
		scope.OrgID,
		scope.Region,
	}, ".")
}

// OpenAuditCache selects the cache database Audit's decorator expects.
//
// It exists so the namespace is never spelled twice. Calling SetDatabase by hand
// with a name assembled elsewhere is the one way to get a decorator whose keys do
// not match its scope, and assertNamespace would then refuse it — correctly, but
// after the fact.
func OpenAuditCache(ctx context.Context, p cache.Provider, scope AuditScope) (*cache.DB, error) {
	if err := scope.validate(); err != nil {
		return nil, err
	}
	return p.SetDatabase(ctx, AuditNamespace(scope))
}

// Audit caching: INDEXED over audits.
// Resource pattern: orgs/{org}/audits/{audit}
// No TTL: entries persist until invalidated, which for a read-through cache means it keeps every id it has ever loaded. Set (cache.v1.cache).ttl unless that is deliberate.
//
// The decorator embeds the store interface, so anything not listed below — List,
// Count, and any method protoc-gen-store adds later — passes straight through
// uncached. That is deliberate: a list result keyed by its filter is a different
// cache with different invalidation, and silently serving one from here would be
// the kind of correctness bug a cache is not supposed to introduce.
type cachedAuditStore struct {
	// Embedded so unlisted methods delegate. Overridden methods below shadow it.
	tenancy.AuditStoreIface

	inner tenancy.AuditStoreIface
	aside cache.Aside
	opts  options
}

// Compile-time proof that the decorator still satisfies the contract it wraps.
// Without it, a signature drifting from AuditStoreIface would only break in whatever
// package wires the two together.
var _ tenancy.AuditStoreIface = (*cachedAuditStore)(nil)

// NewCachedAuditStore returns a read-through INDEXED view over inner.
//
// It returns an error rather than panicking because everything it checks is a
// deployment fact rather than a programming one: which backend is behind the
// cache, which namespace the database was opened under, whether the scope is
// populated. Those are knowable only at wiring time, and a process that cannot
// cache correctly should say so and exit, not crash mid-request later.
func NewCachedAuditStore(
	ctx context.Context,
	inner tenancy.AuditStoreIface,
	db *cache.DB,
	scope AuditScope,
	opts ...Option,
) (tenancy.AuditStoreIface, error) {
	if inner == nil {
		return nil, errors.New("cache: NewCachedAuditStore: inner store is nil")
	}
	if db == nil {
		return nil, errors.New("cache: NewCachedAuditStore: cache database is nil")
	}
	if err := scope.validate(); err != nil {
		return nil, err
	}
	if err := assertNamespace(db, AuditNamespace(scope), "tenancy.v1.Audit"); err != nil {
		return nil, err
	}
	if err := assertSets(ctx, db, "tenancy.v1.Audit", "INDEXED", "__cache_capability_probe"); err != nil {
		return nil, err
	}

	s := &cachedAuditStore{
		AuditStoreIface: inner,
		inner:           inner,
		opts:            newOptions(opts),
	}
	s.aside = db.Aside(s.load)
	return s, nil
}

// load is the read-through loader: the cache's only route back to the store.
func (s *cachedAuditStore) load(ctx context.Context, id string) (any, error) {
	m, err := s.inner.GetByID(ctx, id)
	if err != nil {
		return nil, s.opts.asNotFound(err)
	}
	return m, nil
}

// Invalidate drops this Audit's entry, and any remembered absence with it.
// It is also what makes the decorator usable as an Invalidator on another
// resource's edge.
func (s *cachedAuditStore) Invalidate(ctx context.Context, id string) error {
	return s.aside.Invalidate(ctx, id)
}

// GetByID serves from the cache, loading through to the store on a miss.
//
// Concurrent misses on one id collapse into a single load, and no caller blocks
// past its own context — both are core's, not this file's.
func (s *cachedAuditStore) GetByID(ctx context.Context, id string) (*tenancy.Audit, error) {
	var out tenancy.Audit
	if err := s.aside.GetOrLoad(ctx, id, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create writes through to the store, then warms the entry it just created.
//
// Refresh rather than Invalidate: the row exists and is about to be read, and
// dropping the entry instead would leave every reader arriving next to miss at
// once — the thundering miss that a cache is supposed to prevent.
func (s *cachedAuditStore) Create(ctx context.Context, m *tenancy.Audit) error {
	if err := s.inner.Create(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// Update writes through, then refreshes rather than dropping, for the same
// reason Create does.
func (s *cachedAuditStore) Update(ctx context.Context, m *tenancy.Audit) error {
	if err := s.inner.Update(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// DeleteByID removes the row, then the entry.
//
// Invalidate, not Refresh: there is nothing to refresh to, and Invalidate also
// drops any remembered absence — so a row deleted and recreated does not stay
// invisible until that absence expires on its own.
func (s *cachedAuditStore) DeleteByID(ctx context.Context, id string) error {
	if err := s.inner.DeleteByID(ctx, id); err != nil {
		return err
	}
	return s.opts.afterWrite(ctx, "tenancy.v1.Audit", "invalidate", s.aside.Invalidate(ctx, id))
}

// after runs the cache-side work a write implies: refresh this entry, refile its
// indexes, and fire this resource's declared invalidation edges.
//
// The edges are straight-line calls, one per declared edge, in the order the spec
// declared them. Nothing here walks a graph.
//
// Every step is routed through options.afterWrite, because every step runs after
// s.inner has already committed. By default a failure in any of them is reported
// to WithWriteErrors and does not fail the caller's write — see afterWrite for
// why that is the default and what it costs. One consequence is visible here: on
// the default path a failing step does not skip the ones after it, so a broken
// edge cannot silently cancel the others.
//
// They run in sequence, one round trip each. Firing them concurrently would cut
// the latency of a write with several edges, and is deliberately not done: the
// order is the order the spec declared, the failure attribution stays simple, and
// a decorator is not the place to introduce a goroutine per write. If the edge
// count on a resource ever makes this hurt, the answer the edge set was emitted
// as data for is a CDC consumer, not a fan-out here.
func (s *cachedAuditStore) after(ctx context.Context, m *tenancy.Audit) error {
	if err := s.opts.afterWrite(ctx, "tenancy.v1.Audit", "refresh",
		s.aside.Refresh(ctx, m.ID)); err != nil {
		return err
	}
	return nil
}

// WARNING: tenancy.v1.Session: index on "status", which nothing marks unique — neither store.v1 nor the AIP annotations. Every entry sharing a value lands in one key, so an index on something low-cardinality (a tenant, a status, a version) becomes a hot key that every write to that field must reach.

// SessionScope is the parent scope a Session decorator is bound to.
//
// A decorator is constructed per scope, not per process: the namespace — and so
// every key under it — is parameterized by these values, which is what keeps one
// parent's entries unreachable from another's.
type SessionScope struct {
	// Tenant is the {org} segment of the resource pattern. Every key this decorator reads or writes is namespaced by it, which is what keeps one org's entries unreachable from another's.
	Tenant string
}

// validate rejects a scope that cannot name a keyspace.
//
// An empty value would collapse two parents into one namespace, which is the
// isolation failure this whole mechanism exists to prevent — silently, since the
// resulting name is still a valid name. A ':' would let two differently-spelled
// scopes address the same keys, for the reason core.CheckNamespace gives.
func (s SessionScope) validate() error {
	if s.Tenant == "" {
		return errors.New("cache: tenancy.v1.Session: scope field Tenant is empty; " +
			"an empty scope value collapses every parent into one namespace, which removes the " +
			"isolation the org segment exists to provide")
	}
	if strings.Contains(s.Tenant, ":") {
		return fmt.Errorf("cache: scope field Tenant = %q contains ':', which the cache "+
			"keyspace uses to join the prefix to the namespace — two scopes spelled differently "+
			"would address the same keys", s.Tenant)
	}
	return nil
}

// SessionNamespace returns the namespace Session's keyspace is built under.
//
// This is the value to pass to Provider.SetDatabase. It is the whole of what this
// generator emits about key layout: core owns everything below it.
func SessionNamespace(scope SessionScope) string {
	return strings.Join([]string{
		"tenancy.v1.session",
		"org",
		scope.Tenant,
	}, ".")
}

// OpenSessionCache selects the cache database Session's decorator expects.
//
// It exists so the namespace is never spelled twice. Calling SetDatabase by hand
// with a name assembled elsewhere is the one way to get a decorator whose keys do
// not match its scope, and assertNamespace would then refuse it — correctly, but
// after the fact.
func OpenSessionCache(ctx context.Context, p cache.Provider, scope SessionScope) (*cache.DB, error) {
	if err := scope.validate(); err != nil {
		return nil, err
	}
	return p.SetDatabase(ctx, SessionNamespace(scope))
}

// Session caching: INDEXED over sessions.
// Resource pattern: orgs/{org}/sessions/{session}
// Entries live 1m0s; readers block on the loader when one expires.
//
// The decorator embeds the store interface, so anything not listed below — List,
// Count, and any method protoc-gen-store adds later — passes straight through
// uncached. That is deliberate: a list result keyed by its filter is a different
// cache with different invalidation, and silently serving one from here would be
// the kind of correctness bug a cache is not supposed to introduce.
type cachedSessionStore struct {
	// Embedded so unlisted methods delegate. Overridden methods below shadow it.
	tenancy.SessionStoreIface

	inner   tenancy.SessionStoreIface
	aside   cache.Aside
	opts    options
	indexed cache.Indexed
}

// Compile-time proof that the decorator still satisfies the contract it wraps.
// Without it, a signature drifting from SessionStoreIface would only break in whatever
// package wires the two together.
var _ tenancy.SessionStoreIface = (*cachedSessionStore)(nil)

// NewCachedSessionStore returns a read-through INDEXED view over inner.
//
// It returns an error rather than panicking because everything it checks is a
// deployment fact rather than a programming one: which backend is behind the
// cache, which namespace the database was opened under, whether the scope is
// populated. Those are knowable only at wiring time, and a process that cannot
// cache correctly should say so and exit, not crash mid-request later.
func NewCachedSessionStore(
	ctx context.Context,
	inner tenancy.SessionStoreIface,
	db *cache.DB,
	scope SessionScope,
	opts ...Option,
) (tenancy.SessionStoreIface, error) {
	if inner == nil {
		return nil, errors.New("cache: NewCachedSessionStore: inner store is nil")
	}
	if db == nil {
		return nil, errors.New("cache: NewCachedSessionStore: cache database is nil")
	}
	if err := scope.validate(); err != nil {
		return nil, err
	}
	if err := assertNamespace(db, SessionNamespace(scope), "tenancy.v1.Session"); err != nil {
		return nil, err
	}
	if err := assertSets(ctx, db, "tenancy.v1.Session", "INDEXED", "status"); err != nil {
		return nil, err
	}

	s := &cachedSessionStore{
		SessionStoreIface: inner,
		inner:             inner,
		opts:              newOptions(opts),
		indexed:           db.Indexed,
	}
	s.aside = db.Aside(s.load)
	return s, nil
}

// load is the read-through loader: the cache's only route back to the store.
func (s *cachedSessionStore) load(ctx context.Context, id string) (any, error) {
	m, err := s.inner.GetByID(ctx, id)
	if err != nil {
		return nil, s.opts.asNotFound(err)
	}
	return m, nil
}

// Invalidate drops this Session's entry, and any remembered absence with it.
// It is also what makes the decorator usable as an Invalidator on another
// resource's edge.
func (s *cachedSessionStore) Invalidate(ctx context.Context, id string) error {
	return s.aside.Invalidate(ctx, id)
}

// GetByID serves from the cache, loading through to the store on a miss.
//
// Concurrent misses on one id collapse into a single load, and no caller blocks
// past its own context — both are core's, not this file's.
func (s *cachedSessionStore) GetByID(ctx context.Context, id string) (*tenancy.Session, error) {
	var out tenancy.Session
	if err := s.aside.GetOrLoad(ctx, id, &out, cache.TTL(1*time.Minute)); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create writes through to the store, then warms the entry it just created.
//
// Refresh rather than Invalidate: the row exists and is about to be read, and
// dropping the entry instead would leave every reader arriving next to miss at
// once — the thundering miss that a cache is supposed to prevent.
func (s *cachedSessionStore) Create(ctx context.Context, m *tenancy.Session) error {
	if err := s.inner.Create(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// Update writes through, then refreshes rather than dropping, for the same
// reason Create does.
func (s *cachedSessionStore) Update(ctx context.Context, m *tenancy.Session) error {
	if err := s.inner.Update(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// DeleteByID removes the row, then the entry.
//
// Invalidate, not Refresh: there is nothing to refresh to, and Invalidate also
// drops any remembered absence — so a row deleted and recreated does not stay
// invisible until that absence expires on its own.
func (s *cachedSessionStore) DeleteByID(ctx context.Context, id string) error {
	if err := s.inner.DeleteByID(ctx, id); err != nil {
		return err
	}
	// Unfile before dropping the entry: an index member naming an entry that is
	// gone is swept on the next lookup, while an entry no index names is
	// invisible to every lookup.
	if err := s.indexed.Delete(ctx, id); err != nil && !errors.Is(err, cache.ErrNotFound) {
		if ferr := s.opts.afterWrite(ctx, "tenancy.v1.Session", "unfile", err); ferr != nil {
			return ferr
		}
	}
	return s.opts.afterWrite(ctx, "tenancy.v1.Session", "invalidate", s.aside.Invalidate(ctx, id))
}

// after runs the cache-side work a write implies: refresh this entry, refile its
// indexes, and fire this resource's declared invalidation edges.
//
// The edges are straight-line calls, one per declared edge, in the order the spec
// declared them. Nothing here walks a graph.
//
// Every step is routed through options.afterWrite, because every step runs after
// s.inner has already committed. By default a failure in any of them is reported
// to WithWriteErrors and does not fail the caller's write — see afterWrite for
// why that is the default and what it costs. One consequence is visible here: on
// the default path a failing step does not skip the ones after it, so a broken
// edge cannot silently cancel the others.
//
// They run in sequence, one round trip each. Firing them concurrently would cut
// the latency of a write with several edges, and is deliberately not done: the
// order is the order the spec declared, the failure attribution stays simple, and
// a decorator is not the place to introduce a goroutine per write. If the edge
// count on a resource ever makes this hurt, the answer the edge set was emitted
// as data for is a CDC consumer, not a fan-out here.
func (s *cachedSessionStore) after(ctx context.Context, m *tenancy.Session) error {
	if err := s.opts.afterWrite(ctx, "tenancy.v1.Session", "refresh",
		s.aside.Refresh(ctx, m.ID, cache.TTL(1*time.Minute))); err != nil {
		return err
	}
	if err := s.opts.afterWrite(ctx, "tenancy.v1.Session", "refile", s.refile(ctx, m)); err != nil {
		return err
	}
	return nil
}

// refile writes the entry into the Indexed strategy and files it under each
// index, replacing whatever it was filed under before.
//
// Update before Create, rather than Create alone, because only Update refiles.
// Create adds index members; it does not remove the ones already there. So a
// Session whose indexed column *changed* would stay findable under its old
// value until the entry expired — which is the exact bug hand-rolled secondary
// indexes are famous for, and the one core.Indexed.Update exists to avoid. Create
// is the fallback for the entry not being there yet, which is the ordinary case
// on insert.
func (s *cachedSessionStore) refile(ctx context.Context, m *tenancy.Session) error {
	opts := []cache.Option{
		cache.TTL(1 * time.Minute),
	}
	// Status is nullable in the store's model. An unset value is left
	// unfiled rather than filed under "", which would collect every Session
	// missing the field into one key — a hot key made of unrelated entries.
	if m.Status != nil {
		opts = append(opts, cache.Index("status", *m.Status))
	}
	// Token is nullable in the store's model. An unset value is left
	// unfiled rather than filed under "", which would collect every Session
	// missing the field into one key — a hot key made of unrelated entries.
	if m.Token != nil {
		opts = append(opts, cache.Index("token", *m.Token))
	}

	err := s.indexed.Update(ctx, m.ID, m, opts...)
	if !errors.Is(err, cache.ErrNotFound) {
		return err
	}
	// A fresh slice: appending to opts here would write into the array the loop
	// above built, which the Update call above still refers to.
	create := make([]cache.Option, 0, len(opts)+1)
	create = append(create, opts...)
	create = append(create, cache.ID(m.ID))
	_, err = s.indexed.Create(ctx, m, create...)
	return err
}

// ByStatus returns every cached Session filed under "status", which nothing marks unique — every Session sharing a value lands in one key.
//
// It reads the cache only. A miss is an empty slice, not a load: "which entries
// match?" is a different question from "fetch me this one", and answering it from
// the store would mean a query this decorator has no way to write.
func (s *cachedSessionStore) ByStatus(ctx context.Context, v string) ([]tenancy.Session, error) {
	var out []tenancy.Session
	if err := s.indexed.ByIndex(ctx, "status", v, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// IDsByStatus returns the ids filed under "status", which nothing marks unique — every Session sharing a value lands in one key., for when decoding every value
// would be waste.
func (s *cachedSessionStore) IDsByStatus(ctx context.Context, v string) ([]string, error) {
	return s.indexed.IDsByIndex(ctx, "status", v)
}

// DeleteByStatus drops every cached entry filed under "status", which nothing marks unique — every Session sharing a value lands in one key. and reports how many
// went. It touches the cache only — the rows are untouched.
func (s *cachedSessionStore) DeleteByStatus(ctx context.Context, v string) (int, error) {
	return s.indexed.DeleteByIndex(ctx, "status", v)
}

// ByToken returns every cached Session filed under "token".
//
// It reads the cache only. A miss is an empty slice, not a load: "which entries
// match?" is a different question from "fetch me this one", and answering it from
// the store would mean a query this decorator has no way to write.
func (s *cachedSessionStore) ByToken(ctx context.Context, v string) ([]tenancy.Session, error) {
	var out []tenancy.Session
	if err := s.indexed.ByIndex(ctx, "token", v, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// IDsByToken returns the ids filed under "token"., for when decoding every value
// would be waste.
func (s *cachedSessionStore) IDsByToken(ctx context.Context, v string) ([]string, error) {
	return s.indexed.IDsByIndex(ctx, "token", v)
}

// DeleteByToken drops every cached entry filed under "token". and reports how many
// went. It touches the cache only — the rows are untouched.
func (s *cachedSessionStore) DeleteByToken(ctx context.Context, v string) (int, error) {
	return s.indexed.DeleteByIndex(ctx, "token", v)
}
