// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cache/v1/annotations.proto

package cachepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_cache_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*CacheDefaults)(nil),
		Field:         52000,
		Name:          "cache.v1.cache_defaults",
		Tag:           "bytes,52000,opt,name=cache_defaults",
		Filename:      "cache/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*CacheOptions)(nil),
		Field:         52001,
		Name:          "cache.v1.cache",
		Tag:           "bytes,52001,opt,name=cache",
		Filename:      "cache/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*IndexOptions)(nil),
		Field:         52002,
		Name:          "cache.v1.cache_index",
		Tag:           "bytes,52002,opt,name=cache_index",
		Filename:      "cache/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ScopeOptions)(nil),
		Field:         52003,
		Name:          "cache.v1.cache_scope",
		Tag:           "bytes,52003,opt,name=cache_scope",
		Filename:      "cache/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// cache_defaults supplies the per-file defaults every cached resource in the
	// file inherits unless it overrides them.
	//
	// optional cache.v1.CacheDefaults cache_defaults = 52000;
	E_CacheDefaults = &file_cache_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// cache marks a resource as cached and configures how.
	//
	//	option (cache.v1.cache) = {
	//	  enabled: true
	//	  strategy: STRATEGY_ASIDE
	//	  ttl: {seconds: 300}
	//	};
	//
	// optional cache.v1.CacheOptions cache = 52001;
	E_Cache = &file_cache_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// cache_index files this field as a secondary index. The resource must be
	// STRATEGY_INDEXED; the generator refuses otherwise rather than emitting an
	// accessor that would report ErrUnsupported on every backend.
	//
	//	string isbn = 4 [(cache.v1.cache_index) = {}];
	//
	// optional cache.v1.IndexOptions cache_index = 52002;
	E_CacheIndex = &file_cache_v1_annotations_proto_extTypes[2]
	// cache_scope binds this field into the resource's cache namespace, so every
	// key is parameterized by its value.
	//
	//	string author_id = 3 [(cache.v1.cache_scope) = {}];
	//
	// A resource whose AIP pattern has a parent segment must bind it, here or in
	// (cache.v1.cache).namespace. The generator hard-errors otherwise: a cache
	// answers before the store is consulted, so an unbound parent segment means
	// the store's row-level scoping never runs.
	//
	// optional cache.v1.ScopeOptions cache_scope = 52003;
	E_CacheScope = &file_cache_v1_annotations_proto_extTypes[3]
)

var File_cache_v1_annotations_proto protoreflect.FileDescriptor

const file_cache_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1acache/v1/annotations.proto\x12\bcache.v1\x1a\x14cache/v1/cache.proto\x1a google/protobuf/descriptor.proto:^\n" +
	"\x0ecache_defaults\x12\x1c.google.protobuf.FileOptions\x18\xa0\x96\x03 \x01(\v2\x17.cache.v1.CacheDefaultsR\rcacheDefaults:O\n" +
	"\x05cache\x12\x1f.google.protobuf.MessageOptions\x18\xa1\x96\x03 \x01(\v2\x16.cache.v1.CacheOptionsR\x05cache:X\n" +
	"\vcache_index\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x96\x03 \x01(\v2\x16.cache.v1.IndexOptionsR\n" +
	"cacheIndex:X\n" +
	"\vcache_scope\x12\x1d.google.protobuf.FieldOptions\x18\xa3\x96\x03 \x01(\v2\x16.cache.v1.ScopeOptionsR\n" +
	"cacheScopeBg\n" +
	"\fcom.cache.v1B\x10AnnotationsProtoP\x01ZCgithub.com/the-protobuf-project/cache/plugin/pb/cachepbv1;cachepbv1b\x06proto3"

var file_cache_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*CacheDefaults)(nil),               // 3: cache.v1.CacheDefaults
	(*CacheOptions)(nil),                // 4: cache.v1.CacheOptions
	(*IndexOptions)(nil),                // 5: cache.v1.IndexOptions
	(*ScopeOptions)(nil),                // 6: cache.v1.ScopeOptions
}
var file_cache_v1_annotations_proto_depIdxs = []int32{
	0, // 0: cache.v1.cache_defaults:extendee -> google.protobuf.FileOptions
	1, // 1: cache.v1.cache:extendee -> google.protobuf.MessageOptions
	2, // 2: cache.v1.cache_index:extendee -> google.protobuf.FieldOptions
	2, // 3: cache.v1.cache_scope:extendee -> google.protobuf.FieldOptions
	3, // 4: cache.v1.cache_defaults:type_name -> cache.v1.CacheDefaults
	4, // 5: cache.v1.cache:type_name -> cache.v1.CacheOptions
	5, // 6: cache.v1.cache_index:type_name -> cache.v1.IndexOptions
	6, // 7: cache.v1.cache_scope:type_name -> cache.v1.ScopeOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_v1_annotations_proto_init() }
func file_cache_v1_annotations_proto_init() {
	if File_cache_v1_annotations_proto != nil {
		return
	}
	file_cache_v1_cache_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_v1_annotations_proto_rawDesc), len(file_cache_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_cache_v1_annotations_proto_goTypes,
		DependencyIndexes: file_cache_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_cache_v1_annotations_proto_extTypes,
	}.Build()
	File_cache_v1_annotations_proto = out.File
	file_cache_v1_annotations_proto_goTypes = nil
	file_cache_v1_annotations_proto_depIdxs = nil
}
