// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cache/v1/cache.proto

package cachepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Strategy selects which of the cache runtime's four shapes a resource is served
// through. There are exactly four because runtime-go/cache implements exactly
// four, and a vocabulary that can express a fifth is a vocabulary that can
// express something nothing will honor.
//
// Two names that belong to other caching literatures are deliberately absent:
//
//   - WRITE_BEHIND. The runtime has no such path. Every write in a generated
//     decorator reaches the store first and the cache second, and an annotation
//     promising otherwise would describe a durability model that does not exist.
//   - REFRESH_AHEAD. This is [CacheOptions.stale], which is the same idea named
//     for what it actually does: past its lease an entry is served as-is and
//     refreshed behind the reader.
type Strategy int32

const (
	// Unset; the file's default applies, and ASIDE if it names none.
	Strategy_STRATEGY_UNSPECIFIED Strategy = 0
	// Read-through over a loader bound to the store. Single-flighted, with
	// negative caching and an optional stale window. The default, and the right
	// answer for a resource read by id.
	Strategy_STRATEGY_ASIDE Strategy = 1
	// Read-through plus secondary indexes, so a resource can be found by a field
	// other than its id. Requires a backend with server-side sets; memcached has
	// none. See [CacheOptions.strategy] on what that costs at construction.
	Strategy_STRATEGY_INDEXED Strategy = 2
	// Whole encoded values, enumerable. One index key holds every id, so this
	// does not shard and does not scale past low millions of entries.
	Strategy_STRATEGY_DOCUMENT Strategy = 3
	// TTL-first storage with no index and nothing to sweep. Scales furthest;
	// gives up enumeration entirely.
	Strategy_STRATEGY_VOLATILE Strategy = 4
)

// Enum value maps for Strategy.
var (
	Strategy_name = map[int32]string{
		0: "STRATEGY_UNSPECIFIED",
		1: "STRATEGY_ASIDE",
		2: "STRATEGY_INDEXED",
		3: "STRATEGY_DOCUMENT",
		4: "STRATEGY_VOLATILE",
	}
	Strategy_value = map[string]int32{
		"STRATEGY_UNSPECIFIED": 0,
		"STRATEGY_ASIDE":       1,
		"STRATEGY_INDEXED":     2,
		"STRATEGY_DOCUMENT":    3,
		"STRATEGY_VOLATILE":    4,
	}
)

func (x Strategy) Enum() *Strategy {
	p := new(Strategy)
	*p = x
	return p
}

func (x Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_v1_cache_proto_enumTypes[0].Descriptor()
}

func (Strategy) Type() protoreflect.EnumType {
	return &file_cache_v1_cache_proto_enumTypes[0]
}

func (x Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strategy.Descriptor instead.
func (Strategy) EnumDescriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

// CacheOptions is the message-level (cache.v1.cache) annotation: whether a
// resource is cached, how, and for how long.
type CacheOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled turns caching on for this resource. It is explicit rather than
	// implied by the presence of the annotation, so a resource can be annotated
	// with a considered configuration and switched off without deleting it — and
	// so that "is this cached?" has one answer to read rather than an absence to
	// interpret.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// strategy selects the runtime shape. Unset takes the file default, then ASIDE.
	Strategy Strategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=cache.v1.Strategy" json:"strategy,omitempty"`
	// ttl is how long an entry stays fresh. Unset takes the file default.
	//
	// A cache with no lease anywhere is a store that only grows, and for ASIDE it
	// is a store that only grows by every id anyone ever asked for. The runtime
	// can be configured to refuse a write that resolved to no expiry
	// ([cache.Config.RequireTTL]); this annotation is where a resource says what
	// its expiry should be.
	Ttl *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// stale is how much longer past ttl an expired entry may be served while it is
	// refreshed behind the reader.
	//
	// Zero keeps reads blocking on expiry, which is the safe default: serving
	// slightly old data is a policy, not an optimization to switch on quietly.
	// Non-zero needs a backend that can report a remaining lease (core.Leases) —
	// memcached stores an expiry and honors it but will never say what is left of
	// it. The generated constructor asserts that at construction.
	Stale *durationpb.Duration `protobuf:"bytes,4,opt,name=stale,proto3" json:"stale,omitempty"`
	// negative_ttl is how long the absence of a resource is remembered, so a
	// stream of requests for something that does not exist stops reaching the
	// store. Unset takes the runtime's own default.
	NegativeTtl *durationpb.Duration `protobuf:"bytes,5,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	// namespace overrides the namespace derived from the AIP resource type.
	//
	// It must bind every parent segment of the resource's pattern, written as
	// "{segment}" — a pattern of "users/{user}/documents/{document}" requires
	// "{user}" to appear here, or on a field marked (cache.v1.cache_scope). This
	// is the one thing the generator refuses to emit without: a cache answers
	// before the store is consulted, so an unbound parent segment means the
	// store's row-level scoping never runs and one tenant reads another's rows.
	//
	// It may not contain ':' — that character joins the prefix to the namespace in
	// the runtime's keyspace, so allowing one would let two configurations that
	// were never meant to meet address the same keys.
	Namespace     string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheOptions) Reset() {
	*x = CacheOptions{}
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheOptions) ProtoMessage() {}

func (x *CacheOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheOptions.ProtoReflect.Descriptor instead.
func (*CacheOptions) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CacheOptions) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_STRATEGY_UNSPECIFIED
}

func (x *CacheOptions) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *CacheOptions) GetStale() *durationpb.Duration {
	if x != nil {
		return x.Stale
	}
	return nil
}

func (x *CacheOptions) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

func (x *CacheOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// CacheDefaults is the file-level (cache.v1.cache_defaults) annotation: the
// settings every cached resource in the file inherits unless it says otherwise.
//
// It exists because ttl is the option most likely to be identical across a
// package and most costly to get wrong by omission. A per-message value always
// wins; this only fills what a message left unset.
type CacheDefaults struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// strategy applied to resources that name none.
	Strategy Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=cache.v1.Strategy" json:"strategy,omitempty"`
	// ttl applied to resources that name none.
	Ttl *durationpb.Duration `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// stale applied to resources that name none.
	Stale *durationpb.Duration `protobuf:"bytes,3,opt,name=stale,proto3" json:"stale,omitempty"`
	// negative_ttl applied to resources that name none.
	NegativeTtl   *durationpb.Duration `protobuf:"bytes,4,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDefaults) Reset() {
	*x = CacheDefaults{}
	mi := &file_cache_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDefaults) ProtoMessage() {}

func (x *CacheDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDefaults.ProtoReflect.Descriptor instead.
func (*CacheDefaults) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheDefaults) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_STRATEGY_UNSPECIFIED
}

func (x *CacheDefaults) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *CacheDefaults) GetStale() *durationpb.Duration {
	if x != nil {
		return x.Stale
	}
	return nil
}

func (x *CacheDefaults) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

// IndexOptions is the field-level (cache.v1.cache_index) annotation: file this
// field as a secondary index on an INDEXED resource.
//
// Every indexed field is another set, another single key, and another node that
// every write to that field must reach. An index on something low-cardinality —
// a tenant, a status, a version — puts every entry sharing that value into one
// key, which is where this stops scaling first and does it quietly. The
// generator warns when it can tell (a column store.v1 did not mark unique).
//
// AIP-123 wants a google.api.resource on any message carrying a `name` field,
// because in a resource-oriented API that field is the resource name. This is an
// annotation payload, not a resource: it is never stored, never addressed, and
// never returned by an RPC, and `name` here is the index's name in the runtime's
// keyspace. Annotating it as a resource would be describing something that does
// not exist, so the rule is turned off for this message and nowhere else.
//
// (-- api-linter: core::0123::resource-annotation=disabled
//
//	aip.dev/not-precedent: This is an option message, not an API resource. --)
type IndexOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name overrides the index field name used in the runtime's keyspace.
	// Defaults to the column name, which is what keeps a generated index
	// addressable by anything else reading the same schema.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexOptions) Reset() {
	*x = IndexOptions{}
	mi := &file_cache_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOptions) ProtoMessage() {}

func (x *IndexOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOptions.ProtoReflect.Descriptor instead.
func (*IndexOptions) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *IndexOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ScopeOptions is the field-level (cache.v1.cache_scope) annotation: bind this
// field into the resource's cache namespace.
//
// This is the security-relevant annotation in cache.v1. Marking a field scope
// means the namespace — and therefore every key under it — is parameterized by
// that field's value, so entries for one parent are unreachable from a decorator
// constructed for another.
type ScopeOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// segment names the parent segment of the resource pattern this field binds,
	// written without braces ("user" for "users/{user}/documents/{document}").
	//
	// Unset infers it: a field named "<segment>_id" or "<segment>", or one whose
	// (google.api.resource_reference) names the parent resource type. Set it when
	// the field's name does not follow from the pattern, and the generator will
	// hold you to it rather than guessing.
	Segment       string `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeOptions) Reset() {
	*x = ScopeOptions{}
	mi := &file_cache_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeOptions) ProtoMessage() {}

func (x *ScopeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeOptions.ProtoReflect.Descriptor instead.
func (*ScopeOptions) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{3}
}

func (x *ScopeOptions) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

var File_cache_v1_cache_proto protoreflect.FileDescriptor

const file_cache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x14cache/v1/cache.proto\x12\bcache.v1\x1a\x1egoogle/protobuf/duration.proto\"\x92\x02\n" +
	"\fCacheOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12.\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x12.cache.v1.StrategyR\bstrategy\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12/\n" +
	"\x05stale\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x05stale\x12<\n" +
	"\fnegative_ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtl\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\"\xe9\x01\n" +
	"\rCacheDefaults\x12.\n" +
	"\bstrategy\x18\x01 \x01(\x0e2\x12.cache.v1.StrategyR\bstrategy\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12/\n" +
	"\x05stale\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05stale\x12<\n" +
	"\fnegative_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtlJ\x04\b\x05\x10\x06R\x06prefix\"\"\n" +
	"\fIndexOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fScopeOptions\x12\x18\n" +
	"\asegment\x18\x01 \x01(\tR\asegment*|\n" +
	"\bStrategy\x12\x18\n" +
	"\x14STRATEGY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTRATEGY_ASIDE\x10\x01\x12\x14\n" +
	"\x10STRATEGY_INDEXED\x10\x02\x12\x15\n" +
	"\x11STRATEGY_DOCUMENT\x10\x03\x12\x15\n" +
	"\x11STRATEGY_VOLATILE\x10\x04Ba\n" +
	"\fcom.cache.v1B\n" +
	"CacheProtoP\x01ZCgithub.com/the-protobuf-project/cache/plugin/pb/cachepbv1;cachepbv1b\x06proto3"

var (
	file_cache_v1_cache_proto_rawDescOnce sync.Once
	file_cache_v1_cache_proto_rawDescData []byte
)

func file_cache_v1_cache_proto_rawDescGZIP() []byte {
	file_cache_v1_cache_proto_rawDescOnce.Do(func() {
		file_cache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)))
	})
	return file_cache_v1_cache_proto_rawDescData
}

var file_cache_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cache_v1_cache_proto_goTypes = []any{
	(Strategy)(0),               // 0: cache.v1.Strategy
	(*CacheOptions)(nil),        // 1: cache.v1.CacheOptions
	(*CacheDefaults)(nil),       // 2: cache.v1.CacheDefaults
	(*IndexOptions)(nil),        // 3: cache.v1.IndexOptions
	(*ScopeOptions)(nil),        // 4: cache.v1.ScopeOptions
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_cache_v1_cache_proto_depIdxs = []int32{
	0, // 0: cache.v1.CacheOptions.strategy:type_name -> cache.v1.Strategy
	5, // 1: cache.v1.CacheOptions.ttl:type_name -> google.protobuf.Duration
	5, // 2: cache.v1.CacheOptions.stale:type_name -> google.protobuf.Duration
	5, // 3: cache.v1.CacheOptions.negative_ttl:type_name -> google.protobuf.Duration
	0, // 4: cache.v1.CacheDefaults.strategy:type_name -> cache.v1.Strategy
	5, // 5: cache.v1.CacheDefaults.ttl:type_name -> google.protobuf.Duration
	5, // 6: cache.v1.CacheDefaults.stale:type_name -> google.protobuf.Duration
	5, // 7: cache.v1.CacheDefaults.negative_ttl:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cache_v1_cache_proto_init() }
func file_cache_v1_cache_proto_init() {
	if File_cache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_v1_cache_proto_goTypes,
		DependencyIndexes: file_cache_v1_cache_proto_depIdxs,
		EnumInfos:         file_cache_v1_cache_proto_enumTypes,
		MessageInfos:      file_cache_v1_cache_proto_msgTypes,
	}.Build()
	File_cache_v1_cache_proto = out.File
	file_cache_v1_cache_proto_goTypes = nil
	file_cache_v1_cache_proto_depIdxs = nil
}
