// Code generated by protoc-gen-cache. DO NOT EDIT.
// versions:
// 	protoc-gen-cache test
// 	protoc (unknown)
// source: bookstore.proto
//
// database: bookstore_db
// schema:   bookstore_v1
//
// annotations: entity.v1 test, cache.v1 test
// engine:      protokit test
// runtime:     github.com/the-protobuf-project/runtime-go/cache
//
// cache — https://github.com/the-protobuf-project/cache

package bookstorev1cache

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/the-protobuf-project/cache/examples/generated/gorm/bookstore_db/bookstorev1"
	"github.com/the-protobuf-project/runtime-go/cache"
)

// This package is the *typed* path onto the cache runtime: one decorator per
// cached resource, implementing the store interface protoc-gen-store generated,
// so a caller narrows to the interface and stops caring which one it holds.
//
// There is a second path, and they are alternatives rather than layers. The
// untyped one is runtime-go/database/cached.Wrap, which decorates a store.Driver
// at the byte level and knows nothing about these types. Stacking both would put
// two caches on one read: the decorator would hit, or miss and call a store whose
// driver caches the same row again under a different key, and an invalidation
// through one would leave the other serving what it just invalidated. Pick one.
//
// # What is not here
//
// Key strings. runtime-go/cache/core/keyspace.go owns key layout entirely. What
// this file generates is the *namespace* the keyspace is built under — the value
// handed to Provider.SetDatabase — and never a key inside it. Two keyspaces that
// have to agree is one keyspace too many.
//
// Singleflight, negative caching, TTL enforcement, stale-while-revalidate and
// index maintenance are all in core, and none of them is reimplemented here.

// Invalidator is the one method an invalidation edge needs.
//
// cache.Aside satisfies it, and so does every decorator in this package, so
// wiring an edge is passing one to the other rather than introducing a type
// whose only purpose is to be passed.
type Invalidator interface {
	Invalidate(ctx context.Context, id string) error
}

// Edge is one declared invalidation relationship: a write to From makes To's
// entries stale.
//
// The set below is data, not machinery. Nothing in this file reads it — each
// edge is also a named field and a straight-line call, so the blast radius of a
// write is visible where the write is. It is emitted because something else will
// want it: a CDC consumer invalidating from the write-ahead log needs to know
// which entries a row change reaches, and should not have to regenerate this
// package to find out.
type Edge struct {
	// From and To are fully-qualified proto message names.
	From, To string

	// Via is the foreign-key column carrying the relationship.
	Via string

	// Reason is why the edge exists, in one line.
	Reason string
}

// InvalidationEdges is every invalidation edge originating in the bookstore_v1
// schema, sorted by (from, to, via).
var InvalidationEdges = []Edge{
	{
		From:   "bookstore.v1.Book",
		To:     "bookstore.v1.Author",
		Via:    "author_id",
		Reason: "Book.author_id references Author, so writing a Book changes what that Author preloads",
	},
}

// Option tunes a decorator at construction.
type Option func(*options)

type options struct {
	notFound     func(error) bool
	writeErrors  func(ctx context.Context, resource, op string, err error)
	strictWrites bool
}

// WithNotFound teaches the decorators which store error means "this row does not
// exist", so an absence can be cached.
//
// It has to be supplied because this package cannot ask. Negative caching —
// remembering that something is missing, so a stream of requests for it stops
// reaching the database — engages only when the loader returns an error wrapping
// cache.ErrNotFound, and the generated store returns its driver's error
// unchanged (gorm.ErrRecordNotFound). Translating that here would mean importing
// the driver into generated cache code, which is the coupling this whole
// arrangement exists to avoid.
//
// Without it everything still works: a missing row propagates its error to the
// caller and nothing is cached. What you lose is the protection against a client
// walking ids that do not exist, which is the case negative caching is for.
//
//	store, err := NewCachedAuthorStore(ctx, inner, db,
//	    WithNotFound(func(err error) bool { return errors.Is(err, gorm.ErrRecordNotFound) }))
func WithNotFound(fn func(error) bool) Option {
	return func(o *options) { o.notFound = fn }
}

func newOptions(opts []Option) options {
	var o options
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	return o
}

// asNotFound translates a loader error into one the runtime will cache as an
// absence, leaving every other error alone.
func (o options) asNotFound(err error) error {
	if err == nil || o.notFound == nil || !o.notFound(err) {
		return err
	}
	return fmt.Errorf("%w: %w", cache.ErrNotFound, err)
}

// WithWriteErrors observes cache failures that happen *after* a store write has
// already committed — a refresh, a refile, an edge invalidation.
//
// By default those failures do not reach the caller (see afterWrite), which
// means that without this option they are invisible. That is the trade: the
// alternative default is worse, but silence is not free, and a cache whose
// invalidations have been quietly failing for a week is a cache serving stale
// reads nobody has a signal for. Wire this to a counter or a log line.
//
//	store, err := NewCachedAuthorStore(ctx, inner, db,
//	    WithWriteErrors(func(ctx context.Context, resource, op string, err error) {
//	        slog.ErrorContext(ctx, "cache write-side failure",
//	            "resource", resource, "op", op, "err", err)
//	    }))
func WithWriteErrors(fn func(ctx context.Context, resource, op string, err error)) Option {
	return func(o *options) { o.writeErrors = fn }
}

// WithStrictWrites makes a post-commit cache failure fail the write call.
//
// This is the opposite trade to the default, and it is the right one only when
// serving a stale read is worse than a caller believing a write failed that did
// not. Note what it cannot do: the row is already committed by the time anything
// here runs, so this reports the failure, it does not undo it. A caller that
// retries on the error will write twice.
func WithStrictWrites() Option {
	return func(o *options) { o.strictWrites = true }
}

// afterWrite decides what a committed write does about a cache error that
// followed it.
//
// The default is to report it to the observer, if there is one, and otherwise
// swallow it — and that default is the one deliberate asymmetry in this file, so
// it is worth stating why rather than leaving it to be discovered.
//
// Everything routed through here runs *after* s.inner has already committed the
// row. Returning the error to the caller therefore says "your write failed" about
// a write that succeeded, and the ordinary response to that is a retry — which
// creates a second row, or clobbers a concurrent update, for what was a blip in
// a cache. The failure mode of swallowing is different in kind: an entry stays
// stale until its TTL expires. Bounded, recoverable, and invisible only to
// someone who did not wire WithWriteErrors.
//
// The bound is what makes the trade work, so mind the case that has none: a
// resource with no (cache.v1.cache).ttl keeps entries until something invalidates
// them, and a dropped invalidation there is not stale-for-a-minute but stale
// until the next successful write. Each decorator's doc comment says whether its
// resource has a TTL.
//
// WithStrictWrites restores the other behavior for callers who want it.
func (o options) afterWrite(ctx context.Context, resource, op string, err error) error {
	if err == nil {
		return nil
	}
	if o.writeErrors != nil {
		o.writeErrors(ctx, resource, op, err)
	}
	if o.strictWrites {
		return fmt.Errorf("cache: %s: %s failed after the store write had already committed: %w",
			resource, op, err)
	}
	return nil
}

// assertNamespace is what makes a generated namespace a guarantee rather than a
// suggestion.
//
// A *cache.DB arrives already bound to whatever namespace the caller selected it
// under, and nothing in the type says which. If it is not the one this resource's
// keys were derived for, every read and write in this decorator addresses a
// keyspace the generator never reasoned about — which for a scoped resource means
// the isolation it exists to provide is simply absent. cache.DB.Name is the only
// handle on that, so it is checked here, once, before a decorator exists at all.
func assertNamespace(db *cache.DB, want, resource string) error {
	if db.Name == want {
		return nil
	}
	if db.Name == "" {
		return fmt.Errorf("cache: %s: this cache database was selected by index, not by name, "+
			"so it carries no namespace and the one this decorator's keys are derived for (%q) "+
			"cannot be enforced.\n\nSelect it with Provider.SetDatabase(ctx, %s) instead of "+
			"SelectIndex", resource, want, namespaceFuncName(resource))
	}
	return fmt.Errorf("cache: %s: this cache database is namespaced %q, but this decorator's keys "+
		"are derived under %q.\n\nEvery read and write would address a keyspace other than the one "+
		"generated for this resource. Select the database with Provider.SetDatabase(ctx, %s)",
		resource, db.Name, want, namespaceFuncName(resource))
}

// namespaceFuncName names the generated helper in an error message, so the fix
// is spelled out rather than described.
func namespaceFuncName(resource string) string {
	if i := strings.LastIndex(resource, "."); i >= 0 {
		return resource[i+1:] + "Namespace(...)"
	}
	return "the resource's Namespace function"
}

// assertSets fails construction when the driver behind db has no server-side
// sets.
//
// The strategies that need them do not degrade without them — core refuses, per
// operation, with ErrUnsupported — so a decorator built on a setless backend is
// one whose index accessors all fail at runtime, on a code path a test with a
// real Redis will never reach. Better to refuse at startup, naming the resource
// and the capability, than to hand back something that compiles and cannot work.
//
// It probes rather than asks because there is nothing to ask. core resolves a
// driver's capabilities once, at construction, and keeps them private; *cache.DB
// exposes the four strategies and no report of what is behind them. IDsByIndex on
// an empty value is the cheapest question that has the answer in it: a driver with
// no sets refuses before touching the network, and one with sets answers with an
// empty result.
func assertSets(ctx context.Context, db *cache.DB, resource, strategy, probe string) error {
	if _, err := db.Indexed.IDsByIndex(ctx, probe, ""); errors.Is(err, cache.ErrUnsupported) {
		return fmt.Errorf("cache: %s is configured as %s, which requires core.Sets, and the %s "+
			"backend behind this cache database does not implement it: %w\n\n"+
			"A backend with no server-side sets cannot maintain a secondary index or enumerate "+
			"entries. Either move this resource to STRATEGY_ASIDE or STRATEGY_VOLATILE, or wire "+
			"it to a backend with sets (redis, dragonfly).",
			resource, strategy, db.Backend, err)
	}
	return nil
}

// assertLeases fails construction when the driver cannot report a remaining TTL.
//
// A stale window is served by reading how much of an entry's lease is left.
// Memcache stores an expiry and honors it but will never say what remains, so a
// resource configured with (cache.v1.cache).stale cannot behave as configured
// there — it would silently fall back to blocking every reader at the moment the
// key expires, which is precisely the traffic spike stale exists to absorb.
func assertLeases(ctx context.Context, db *cache.DB, resource string) error {
	if _, err := db.Volatile.TTL(ctx, "__cache_capability_probe"); errors.Is(err, cache.ErrUnsupported) {
		return fmt.Errorf("cache: %s sets (cache.v1.cache).stale, which requires core.Leases, and "+
			"the %s backend behind this cache database does not implement it: %w\n\n"+
			"Serving an entry past its lease means reading what is left of that lease, and this "+
			"backend's protocol never reports one. Either drop stale for this resource or wire it "+
			"to a backend with leases (redis, dragonfly).",
			resource, db.Backend, err)
	}
	return nil
}

// authorNamespace is the fixed namespace for Author: its pattern has
// no parent segment and no field is forced into scope, so nothing parameterizes it.
const authorNamespace = "bookstore.v1.author"

// AuthorNamespace returns the namespace Author's keyspace is built under.
//
// This is the value to pass to Provider.SetDatabase. It is the whole of what this
// generator emits about key layout: core owns everything below it.
func AuthorNamespace() string {
	return authorNamespace
}

// OpenAuthorCache selects the cache database Author's decorator expects.
//
// It exists so the namespace is never spelled twice. Calling SetDatabase by hand
// with a name assembled elsewhere is the one way to get a decorator whose keys do
// not match its scope, and assertNamespace would then refuse it — correctly, but
// after the fact.
func OpenAuthorCache(ctx context.Context, p cache.Provider) (*cache.DB, error) {
	return p.SetDatabase(ctx, AuthorNamespace())
}

// Author caching: ASIDE over authors.
// Resource pattern: authors/{author}
// Entries live 5m0s and may be served up to 30s past that while they refresh.
//
// The decorator embeds the store interface, so anything not listed below — List,
// Count, and any method protoc-gen-store adds later — passes straight through
// uncached. That is deliberate: a list result keyed by its filter is a different
// cache with different invalidation, and silently serving one from here would be
// the kind of correctness bug a cache is not supposed to introduce.
type cachedAuthorStore struct {
	// Embedded so unlisted methods delegate. Overridden methods below shadow it.
	bookstorev1.AuthorStoreIface

	inner bookstorev1.AuthorStoreIface
	aside cache.Aside
	opts  options
}

// Compile-time proof that the decorator still satisfies the contract it wraps.
// Without it, a signature drifting from AuthorStoreIface would only break in whatever
// package wires the two together.
var _ bookstorev1.AuthorStoreIface = (*cachedAuthorStore)(nil)

// NewCachedAuthorStore returns a read-through ASIDE view over inner.
//
// It returns an error rather than panicking because everything it checks is a
// deployment fact rather than a programming one: which backend is behind the
// cache, which namespace the database was opened under, whether the scope is
// populated. Those are knowable only at wiring time, and a process that cannot
// cache correctly should say so and exit, not crash mid-request later.
func NewCachedAuthorStore(
	ctx context.Context,
	inner bookstorev1.AuthorStoreIface,
	db *cache.DB,
	opts ...Option,
) (bookstorev1.AuthorStoreIface, error) {
	if inner == nil {
		return nil, errors.New("cache: NewCachedAuthorStore: inner store is nil")
	}
	if db == nil {
		return nil, errors.New("cache: NewCachedAuthorStore: cache database is nil")
	}
	if err := assertNamespace(db, AuthorNamespace(), "bookstore.v1.Author"); err != nil {
		return nil, err
	}
	if err := assertLeases(ctx, db, "bookstore.v1.Author"); err != nil {
		return nil, err
	}

	s := &cachedAuthorStore{
		AuthorStoreIface: inner,
		inner:            inner,
		opts:             newOptions(opts),
	}
	s.aside = db.Aside(s.load)
	return s, nil
}

// load is the read-through loader: the cache's only route back to the store.
func (s *cachedAuthorStore) load(ctx context.Context, id string) (any, error) {
	m, err := s.inner.GetByID(ctx, id)
	if err != nil {
		return nil, s.opts.asNotFound(err)
	}
	return m, nil
}

// Invalidate drops this Author's entry, and any remembered absence with it.
// It is also what makes the decorator usable as an Invalidator on another
// resource's edge.
func (s *cachedAuthorStore) Invalidate(ctx context.Context, id string) error {
	return s.aside.Invalidate(ctx, id)
}

// GetByID serves from the cache, loading through to the store on a miss.
//
// Concurrent misses on one id collapse into a single load, and no caller blocks
// past its own context — both are core's, not this file's.
func (s *cachedAuthorStore) GetByID(ctx context.Context, id string) (*bookstorev1.Author, error) {
	var out bookstorev1.Author
	if err := s.aside.GetOrLoad(ctx, id, &out, cache.TTL(5*time.Minute), cache.Stale(30*time.Second)); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create writes through to the store, then warms the entry it just created.
//
// Refresh rather than Invalidate: the row exists and is about to be read, and
// dropping the entry instead would leave every reader arriving next to miss at
// once — the thundering miss that a cache is supposed to prevent.
func (s *cachedAuthorStore) Create(ctx context.Context, m *bookstorev1.Author) error {
	if err := s.inner.Create(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// Update writes through, then refreshes rather than dropping, for the same
// reason Create does.
func (s *cachedAuthorStore) Update(ctx context.Context, m *bookstorev1.Author) error {
	if err := s.inner.Update(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// DeleteByID removes the row, then the entry.
//
// Invalidate, not Refresh: there is nothing to refresh to, and Invalidate also
// drops any remembered absence — so a row deleted and recreated does not stay
// invisible until that absence expires on its own.
func (s *cachedAuthorStore) DeleteByID(ctx context.Context, id string) error {
	if err := s.inner.DeleteByID(ctx, id); err != nil {
		return err
	}
	return s.opts.afterWrite(ctx, "bookstore.v1.Author", "invalidate", s.aside.Invalidate(ctx, id))
}

// after runs the cache-side work a write implies: refresh this entry, refile its
// indexes, and fire this resource's declared invalidation edges.
//
// The edges are straight-line calls, one per declared edge, in the order the spec
// declared them. Nothing here walks a graph.
//
// Every step is routed through options.afterWrite, because every step runs after
// s.inner has already committed. By default a failure in any of them is reported
// to WithWriteErrors and does not fail the caller's write — see afterWrite for
// why that is the default and what it costs. One consequence is visible here: on
// the default path a failing step does not skip the ones after it, so a broken
// edge cannot silently cancel the others.
//
// They run in sequence, one round trip each. Firing them concurrently would cut
// the latency of a write with several edges, and is deliberately not done: the
// order is the order the spec declared, the failure attribution stays simple, and
// a decorator is not the place to introduce a goroutine per write. If the edge
// count on a resource ever makes this hurt, the answer the edge set was emitted
// as data for is a CDC consumer, not a fan-out here.
func (s *cachedAuthorStore) after(ctx context.Context, m *bookstorev1.Author) error {
	if err := s.opts.afterWrite(ctx, "bookstore.v1.Author", "refresh",
		s.aside.Refresh(ctx, m.ID, cache.TTL(5*time.Minute), cache.Stale(30*time.Second))); err != nil {
		return err
	}
	return nil
}

// BookScope is the parent scope a Book decorator is bound to.
//
// A decorator is constructed per scope, not per process: the namespace — and so
// every key under it — is parameterized by these values, which is what keeps one
// parent's entries unreachable from another's.
type BookScope struct {
	// AuthorID is the {author} segment of the resource pattern. Every key this decorator reads or writes is namespaced by it, which is what keeps one author's entries unreachable from another's.
	AuthorID string
}

// validate rejects a scope that cannot name a keyspace.
//
// An empty value would collapse two parents into one namespace, which is the
// isolation failure this whole mechanism exists to prevent — silently, since the
// resulting name is still a valid name. A ':' would let two differently-spelled
// scopes address the same keys, for the reason core.CheckNamespace gives.
func (s BookScope) validate() error {
	if s.AuthorID == "" {
		return errors.New("cache: bookstore.v1.Book: scope field AuthorID is empty; " +
			"an empty scope value collapses every parent into one namespace, which removes the " +
			"isolation the author segment exists to provide")
	}
	if strings.Contains(s.AuthorID, ":") {
		return fmt.Errorf("cache: scope field AuthorID = %q contains ':', which the cache "+
			"keyspace uses to join the prefix to the namespace — two scopes spelled differently "+
			"would address the same keys", s.AuthorID)
	}
	return nil
}

// BookNamespace returns the namespace Book's keyspace is built under.
//
// This is the value to pass to Provider.SetDatabase. It is the whole of what this
// generator emits about key layout: core owns everything below it.
func BookNamespace(scope BookScope) string {
	return strings.Join([]string{
		"bookstore.v1.book",
		"author",
		scope.AuthorID,
	}, ".")
}

// OpenBookCache selects the cache database Book's decorator expects.
//
// It exists so the namespace is never spelled twice. Calling SetDatabase by hand
// with a name assembled elsewhere is the one way to get a decorator whose keys do
// not match its scope, and assertNamespace would then refuse it — correctly, but
// after the fact.
func OpenBookCache(ctx context.Context, p cache.Provider, scope BookScope) (*cache.DB, error) {
	if err := scope.validate(); err != nil {
		return nil, err
	}
	return p.SetDatabase(ctx, BookNamespace(scope))
}

// BookEdges wires the invalidation edges a write to Book fires.
//
// Each field is a resource whose cached entries a Book write makes stale.
// They are explicit fields rather than a registry the decorator consults because
// the blast radius of a write should be visible at the wiring site — a nil field
// is a decision not to invalidate, made in the open.
type BookEdges struct {
	// Author: Book.author_id references Author, so writing a Book changes what that Author preloads
	// Nil skips it.
	Author Invalidator
}

// Book caching: INDEXED over books.
// Resource pattern: authors/{author}/books/{book}
// Entries live 2m0s; readers block on the loader when one expires.
//
// The decorator embeds the store interface, so anything not listed below — List,
// Count, and any method protoc-gen-store adds later — passes straight through
// uncached. That is deliberate: a list result keyed by its filter is a different
// cache with different invalidation, and silently serving one from here would be
// the kind of correctness bug a cache is not supposed to introduce.
type cachedBookStore struct {
	// Embedded so unlisted methods delegate. Overridden methods below shadow it.
	bookstorev1.BookStoreIface

	inner   bookstorev1.BookStoreIface
	aside   cache.Aside
	opts    options
	indexed cache.Indexed
	edges   BookEdges
}

// Compile-time proof that the decorator still satisfies the contract it wraps.
// Without it, a signature drifting from BookStoreIface would only break in whatever
// package wires the two together.
var _ bookstorev1.BookStoreIface = (*cachedBookStore)(nil)

// NewCachedBookStore returns a read-through INDEXED view over inner.
//
// It returns an error rather than panicking because everything it checks is a
// deployment fact rather than a programming one: which backend is behind the
// cache, which namespace the database was opened under, whether the scope is
// populated. Those are knowable only at wiring time, and a process that cannot
// cache correctly should say so and exit, not crash mid-request later.
func NewCachedBookStore(
	ctx context.Context,
	inner bookstorev1.BookStoreIface,
	db *cache.DB,
	scope BookScope,
	edges BookEdges,
	opts ...Option,
) (bookstorev1.BookStoreIface, error) {
	if inner == nil {
		return nil, errors.New("cache: NewCachedBookStore: inner store is nil")
	}
	if db == nil {
		return nil, errors.New("cache: NewCachedBookStore: cache database is nil")
	}
	if err := scope.validate(); err != nil {
		return nil, err
	}
	if err := assertNamespace(db, BookNamespace(scope), "bookstore.v1.Book"); err != nil {
		return nil, err
	}
	if err := assertSets(ctx, db, "bookstore.v1.Book", "INDEXED", "isbn"); err != nil {
		return nil, err
	}

	s := &cachedBookStore{
		BookStoreIface: inner,
		inner:          inner,
		opts:           newOptions(opts),
		indexed:        db.Indexed,
		edges:          edges,
	}
	s.aside = db.Aside(s.load)
	return s, nil
}

// load is the read-through loader: the cache's only route back to the store.
func (s *cachedBookStore) load(ctx context.Context, id string) (any, error) {
	m, err := s.inner.GetByID(ctx, id)
	if err != nil {
		return nil, s.opts.asNotFound(err)
	}
	return m, nil
}

// Invalidate drops this Book's entry, and any remembered absence with it.
// It is also what makes the decorator usable as an Invalidator on another
// resource's edge.
func (s *cachedBookStore) Invalidate(ctx context.Context, id string) error {
	return s.aside.Invalidate(ctx, id)
}

// GetByID serves from the cache, loading through to the store on a miss.
//
// Concurrent misses on one id collapse into a single load, and no caller blocks
// past its own context — both are core's, not this file's.
func (s *cachedBookStore) GetByID(ctx context.Context, id string) (*bookstorev1.Book, error) {
	var out bookstorev1.Book
	if err := s.aside.GetOrLoad(ctx, id, &out, cache.TTL(2*time.Minute)); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create writes through to the store, then warms the entry it just created.
//
// Refresh rather than Invalidate: the row exists and is about to be read, and
// dropping the entry instead would leave every reader arriving next to miss at
// once — the thundering miss that a cache is supposed to prevent.
func (s *cachedBookStore) Create(ctx context.Context, m *bookstorev1.Book) error {
	if err := s.inner.Create(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// Update writes through, then refreshes rather than dropping, for the same
// reason Create does.
func (s *cachedBookStore) Update(ctx context.Context, m *bookstorev1.Book) error {
	if err := s.inner.Update(ctx, m); err != nil {
		return err
	}
	return s.after(ctx, m)
}

// DeleteByID removes the row, then the entry.
//
// Invalidate, not Refresh: there is nothing to refresh to, and Invalidate also
// drops any remembered absence — so a row deleted and recreated does not stay
// invisible until that absence expires on its own.
func (s *cachedBookStore) DeleteByID(ctx context.Context, id string) error {
	if err := s.inner.DeleteByID(ctx, id); err != nil {
		return err
	}
	// Unfile before dropping the entry: an index member naming an entry that is
	// gone is swept on the next lookup, while an entry no index names is
	// invisible to every lookup.
	if err := s.indexed.Delete(ctx, id); err != nil && !errors.Is(err, cache.ErrNotFound) {
		if ferr := s.opts.afterWrite(ctx, "bookstore.v1.Book", "unfile", err); ferr != nil {
			return ferr
		}
	}
	return s.opts.afterWrite(ctx, "bookstore.v1.Book", "invalidate", s.aside.Invalidate(ctx, id))
}

// after runs the cache-side work a write implies: refresh this entry, refile its
// indexes, and fire this resource's declared invalidation edges.
//
// The edges are straight-line calls, one per declared edge, in the order the spec
// declared them. Nothing here walks a graph.
//
// Every step is routed through options.afterWrite, because every step runs after
// s.inner has already committed. By default a failure in any of them is reported
// to WithWriteErrors and does not fail the caller's write — see afterWrite for
// why that is the default and what it costs. One consequence is visible here: on
// the default path a failing step does not skip the ones after it, so a broken
// edge cannot silently cancel the others.
//
// They run in sequence, one round trip each. Firing them concurrently would cut
// the latency of a write with several edges, and is deliberately not done: the
// order is the order the spec declared, the failure attribution stays simple, and
// a decorator is not the place to introduce a goroutine per write. If the edge
// count on a resource ever makes this hurt, the answer the edge set was emitted
// as data for is a CDC consumer, not a fan-out here.
func (s *cachedBookStore) after(ctx context.Context, m *bookstorev1.Book) error {
	if err := s.opts.afterWrite(ctx, "bookstore.v1.Book", "refresh",
		s.aside.Refresh(ctx, m.ID, cache.TTL(2*time.Minute))); err != nil {
		return err
	}
	if err := s.opts.afterWrite(ctx, "bookstore.v1.Book", "refile", s.refile(ctx, m)); err != nil {
		return err
	}
	// Book.author_id references Author, so writing a Book changes what that Author preloads
	if s.edges.Author != nil {
		if err := s.opts.afterWrite(ctx, "bookstore.v1.Book", "invalidate Author",
			s.edges.Author.Invalidate(ctx, m.AuthorID)); err != nil {
			return err
		}
	}
	return nil
}

// refile writes the entry into the Indexed strategy and files it under each
// index, replacing whatever it was filed under before.
//
// Update before Create, rather than Create alone, because only Update refiles.
// Create adds index members; it does not remove the ones already there. So a
// Book whose indexed column *changed* would stay findable under its old
// value until the entry expired — which is the exact bug hand-rolled secondary
// indexes are famous for, and the one core.Indexed.Update exists to avoid. Create
// is the fallback for the entry not being there yet, which is the ordinary case
// on insert.
func (s *cachedBookStore) refile(ctx context.Context, m *bookstorev1.Book) error {
	opts := []cache.Option{
		cache.TTL(2 * time.Minute),
	}
	// ISBN is nullable in the store's model. An unset value is left
	// unfiled rather than filed under "", which would collect every Book
	// missing the field into one key — a hot key made of unrelated entries.
	if m.ISBN != nil {
		opts = append(opts, cache.Index("isbn", *m.ISBN))
	}

	err := s.indexed.Update(ctx, m.ID, m, opts...)
	if !errors.Is(err, cache.ErrNotFound) {
		return err
	}
	// A fresh slice: appending to opts here would write into the array the loop
	// above built, which the Update call above still refers to.
	create := make([]cache.Option, 0, len(opts)+1)
	create = append(create, opts...)
	create = append(create, cache.ID(m.ID))
	_, err = s.indexed.Create(ctx, m, create...)
	return err
}

// ByISBN returns every cached Book filed under "isbn".
//
// It reads the cache only. A miss is an empty slice, not a load: "which entries
// match?" is a different question from "fetch me this one", and answering it from
// the store would mean a query this decorator has no way to write.
func (s *cachedBookStore) ByISBN(ctx context.Context, v string) ([]bookstorev1.Book, error) {
	var out []bookstorev1.Book
	if err := s.indexed.ByIndex(ctx, "isbn", v, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// IDsByISBN returns the ids filed under "isbn"., for when decoding every value
// would be waste.
func (s *cachedBookStore) IDsByISBN(ctx context.Context, v string) ([]string, error) {
	return s.indexed.IDsByIndex(ctx, "isbn", v)
}

// DeleteByISBN drops every cached entry filed under "isbn". and reports how many
// went. It touches the cache only — the rows are untouched.
func (s *cachedBookStore) DeleteByISBN(ctx context.Context, v string) (int, error) {
	return s.indexed.DeleteByIndex(ctx, "isbn", v)
}
