package generator_test

// golden_test.go pins the generated bytes, and pins that the generated bytes
// import nothing they should not.

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/the-protobuf-project/protokit"
	"github.com/the-protobuf-project/protokit/golden"
	"github.com/the-protobuf-project/protokit/header"

	"github.com/the-protobuf-project/cache/plugin/generator"
)

// storeModule is the import path the golden output's `storepkg` alias resolves
// to. It is the example's generated gorm tree, which is what the committed
// golden was produced against.
const storeModule = "github.com/the-protobuf-project/cache/examples/generated/gorm"

// TestMain sets the tool identity the banner names. The plugin binary does this
// at startup; without it here, every golden would be written by
// "protoc-gen-protokit" and a real run would then disagree with them.
func TestMain(m *testing.M) {
	header.SetTool("protoc-gen-cache")
	os.Exit(m.Run())
}

// testVersions pins every version the banner carries.
//
// All three, not just the plugin's own. A golden compared byte for byte cannot
// contain a version that changes with the build that produced it, and until
// these were injectable two of the three were resolved from the *test binary's*
// build info — so the committed goldens recorded a workspace rather than a
// generator, and went red when that workspace resolved differently. See
// provenance.go.
var testVersions = generator.Versions{Plugin: "test", Entity: "test", Engine: "test"}

// casePlugin builds the plugin for a golden case.
func casePlugin(string) protokit.Plugin {
	return generator.Plugin(storeModule, testVersions, nil)
}

// TestGolden compares each case's output against its committed tree.
func TestGolden(t *testing.T) {
	for _, dir := range cases(t, "cases") {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			golden.RunPluginCase(t, dir, []string{generator.TargetName}, casePlugin)
		})
	}
}

// TestDeterminism requires two builds of one case to produce identical bytes.
//
// Go randomizes map iteration on every range, so a pass that ranges a map
// straight into output differs run to run. A golden test does not reliably catch
// that — the committed file was written by one particular run and a rerun agrees
// with it often enough to look stable. Generating twice in one process is what
// turns "usually passes" into a hard signal.
func TestDeterminism(t *testing.T) {
	for _, dir := range cases(t, "cases") {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			golden.Determinism(t, dir, casePlugin(dir))
		})
	}
}

// TestGeneratedOutputImports asserts that the generated decorator imports only
// the store's generated tree, runtime-go/cache, and the standard library.
//
// This is the output half of the boundary rule, and it is the half that would
// otherwise rot silently. boundary_test.go in the repository root checks what
// *this plugin* links against; nothing there would notice a template that started
// emitting an import of gorm, or of the cache runtime's core package, or of some
// helper module invented to hold a shared type. Every one of those would compile
// in the example and would quietly make the generated package depend on something
// its consumers did not sign up for.
//
// core is worth calling out specifically. It is the same repository as
// runtime-go/cache and it is tempting — it holds Sets, Leases, the keyspace — but
// importing it in generated code would mean the generated code could name a key,
// and a keyspace that two packages can write is a keyspace that will eventually
// disagree with itself.
func TestGeneratedOutputImports(t *testing.T) {
	allowed := map[string]bool{
		"github.com/the-protobuf-project/runtime-go/cache": true,
	}
	const storePrefix = storeModule + "/"

	for _, dir := range cases(t, "cases") {
		goldenDir := filepath.Join(dir, "golden", generator.TargetName)
		t.Run(filepath.Base(dir), func(t *testing.T) {
			files := goFiles(t, goldenDir)
			if len(files) == 0 {
				t.Fatalf("no generated .go files under %s; the check would pass vacuously", goldenDir)
			}
			for _, path := range files {
				for _, imp := range importsOf(t, path) {
					switch {
					case !strings.Contains(imp, "."):
						continue // no dot in the first segment: stdlib
					case allowed[imp]:
						continue
					case strings.HasPrefix(imp, storePrefix):
						continue
					}
					t.Errorf("%s imports %q.\n\n"+
						"Generated cache output may import only the store's generated tree (%s...), "+
						"runtime-go/cache, and the standard library. Anything else becomes a "+
						"dependency of every consumer of the generated package — and if it is "+
						"runtime-go/cache/core, it also means generated code can name a key, which "+
						"core owns outright.",
						mustRel(t, path), imp, storePrefix)
				}
			}
		})
	}
}

// cases lists the case directories under testdata/<kind>.
func cases(t *testing.T, kind string) []string {
	t.Helper()
	root := filepath.Join("testdata", kind)
	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read %s: %v", root, err)
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, filepath.Join(root, e.Name()))
		}
	}
	if len(out) == 0 {
		t.Fatalf("no cases under %s; the suite would pass vacuously", root)
	}
	return out
}

// goFiles lists the .go files under dir, recursively.
func goFiles(t *testing.T, dir string) []string {
	t.Helper()
	var out []string
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".go") {
			out = append(out, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return out
}

// importsOf parses a file's import block.
func importsOf(t *testing.T, path string) []string {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	var out []string
	for _, spec := range f.Imports {
		imp, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		out = append(out, imp)
	}
	return out
}

func mustRel(t *testing.T, path string) string {
	t.Helper()
	rel, err := filepath.Rel("testdata", path)
	if err != nil {
		return path
	}
	return rel
}
